### ISSUE TITLE
Why can't I use 'totals_covered_display' as the coverage figure?

### ISSUE THREAD

**Issue by ThGaskin** [jaywcjlove/coverage-badges-cli#32]
In my `coverage-summary.json`, my `percent_covered` figure comes to e.g. 80.82490239, and the `percent_covered_display` is then the rounded number (80). However, if I do

```yaml
- name: Create coverage badge
  uses: jaywcjlove/coverage-badges-cli@main
  with:
    style: classic
    source: ./coverage/coverage-summary.json
    output: ./coverage/coverage-badge.svg
    jsonPath: totals.percent_covered_display
```
my CI fails with the error

```commandline
totals.percent_covered_display evaluates to "80" and is not a suitable path in the JSON coverage data
```

Why would this be? The long float figure is awkward to use, since it creates a very long and ugly bar :(
